console.log('Hello, World!')

console.log('Commit G - Third Branch')
console.log('Commit H - Third Branch')
console.log('Commit I - Third Branch')
console.log('Commit D - Second Branch')
console.log('Commit E - Second Branch')
console.log('Commit F - Second Branch')
console.log('Commit A - First Branch')
console.log('Commit B - First Branch')
console.log('Commit C - First Branch')

console.log('Commit J - First Branch')
console.log('Commit K - First Branch')
console.log('Commit L - First Branch')
console.log('Commit M - Second Branch')
console.log('Commit N - Second Branch')
console.log('Commit O - Second Branch')
console.log('Commit P - Third Branch')
console.log('Commit Q - Third Branch')
console.log('Commit R - Third Branch')